### ISSUE TITLE
Unknown after_config callback requested: lambda (not found)

### ISSUE THREAD

**Issue by rmontgomery429** [sparkleformation/sfn-lambda#1]
I've added the following to the Gemfile:

`gem 'sfn-lambda', '~> 0.1.0'`

and this to the `.sfn`:

```
callbacks do
  default ['lambda']
end
```

and when I try to `sfn print` or `sfn validate` I get the following error:

`Unknown after_config callback requested: lambda (not found)`

**Comment by rmontgomery429** [comment]
After some investigation into another callback gem https://github.com/sparkleformation/sfn-parameters I noticed one difference that wasn't documented here in this repo.

https://github.com/sparkleformation/sfn-parameters#enable Specifies a `require ['sfn-parameters']` which stood out to me. So I tried adding `require ['sfn-lambda']` in a similar fashion to the callbacks section in our `.sfn` and it appears to work now.

**Comment by chrisroberts** [comment]
Fixed via #2. Thanks!
