### ISSUE TITLE
Handler is being set to the Runtime

### ISSUE THREAD

**Issue by rmontgomery429** [sparkleformation/sfn-lambda#3]
This just appears to an oversight, but the handler is being set to the runtime value. This is evident locally, but after looking at the README you see it in the example output too.

https://github.com/sparkleformation/sfn-lambda#example

```
...
"Handler": "python2.7",
...
```

It also appears that the Runtime is not being set as well which is required.

**Comment by chrisroberts** [comment]
Fixed via #2. Thanks!
