### ISSUE TITLE
ZipFile is not correctly nested under code property

### ISSUE THREAD

**Issue by flemingdp** [sparkleformation/sfn-lambda#6]
ZipFile  is not correctly nested under the code property as stated here
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-code

 "RdsSnapshotsCopyRedmineLambdaFunction":{
      "Type":"AWS::Lambda::Function",
      "Properties":{
        "Handler":"python2.7",
        "FunctionName":"rds_snapshots_copy",
        "ZipFile":"#! /b

Cfn code created with: 
  _lambda!(:rds_snapshots_copy, :Redmine,
          role: attr!(:lambda_rds_snapshots_role, "Arn")).properties.environment do
    variables do
      abc:'abcd'
      es2:'Test2'
    end
  end_

**Comment by webframp** [comment]
Definitely interested in this one too

**Comment by chrisroberts** [comment]
Fixed via #2. Thanks!
